import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import { useState } from 'react';
import Compressor from 'compressorjs';

export default function Home() {
  const [beforeSize, setBeforeSize] = useState(0);
  const [afterSize, setAfterSize] = useState(0);

  const handleChangeImage = (e) => {
    const file = e.target.files[0];
    setBeforeSize(file.size);

    if (!file) {
      return;
    }

    new Compressor(file, {
      quality: 0,
      // convertSize: 500000,
      success(result) {
        setAfterSize(result.size);
      },
      error(err) {
        console.log(err.message);
      },
    });
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <input
          type="file"
          id="file"
          accept="image/*"
          onChange={handleChangeImage}
        />
        <p>元のサイズ：{beforeSize} B</p>
        <p>圧縮後のサイズ：{afterSize} B</p>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
