import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import { useState } from 'react';
import Compressor from 'compressorjs';
import FileSaver from 'file-saver';

export default function Home() {
  const [beforeSize, setBeforeSize] = useState(0);
  const [afterSize, setAfterSize] = useState(0);

  const detectFileType = (arrayBuffer) => {
    const arr = new Uint8Array(arrayBuffer).subarray(0, 4);
    let header = '';

    for (let i = 0; i < arr.length; ++i) {
      header += arr[i].toString(16);
    }

    switch (true) {
      case /^89504e47/.test(header):
        return 'png';
      case /^ffd8ff/.test(header):
        return 'jpeg';
    }
  };

  const handleChangeImage = (e) => {
    const file = e.target.files[0];
    setBeforeSize(file.size);

    if (!file) {
      return;
    }

    const reader = new FileReader();

    reader.onload = (e) => {
      const result = e.target.result;
      const fileType = detectFileType(result);

      switch (fileType) {
        case 'png':
          new Compressor(file, {
            convertSize: 100000,
            success(result) {
              setAfterSize(result.size);
              console.log(result.type);
              FileSaver.saveAs(result, 'image.jpg');
            },
            error(err) {
              console.log(err.message);
            },
          });
          break;
        case 'jpeg':
          new Compressor(file, {
            quality: 0,
            success(result) {
              setAfterSize(result.size);
              console.log(result.type);
              FileSaver.saveAs(result, 'image.jpg');
            },
            error(err) {
              console.log(err.message);
            },
          });
          break;
      }
    };
    reader.readAsArrayBuffer(file);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <input
          type="file"
          id="file"
          accept="image/*"
          onChange={handleChangeImage}
        />
        <p>元のサイズ：{beforeSize} B</p>
        <p>圧縮後のサイズ：{afterSize} B</p>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
